# Generated by Django 5.1.2 on 2024-10-23 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bonus',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Бонусы'),
            preserve_default=False,
        ),
    ]
