from django.urls import path
from .views import (
    ComplectationsViewHome,
    ComplectationViewAdd,
    ComplectationViewEdit,
    ComplectationViewDelete,
    GroupProductViewList,
    GroupProductViewAdd,
    GroupProductViewEdit,
    GroupProductViewDelete,
    ProviderViewList,
    ProviderViewAdd,
    ProviderViewEdit,
    ProviderViewDelete,
    UserViewList,
    UserViewDetale,
    UserViewEdit,
    UserViewAdd,
    UserViewDelete,
    UserPasswordChangeView,
    ProductViewList,
    ProductViewListGroup,
    ProductViewDetale,
    ProductViewAdd,
    ProductViewEdit,
    ProductViewDelete,
    ProductViewPDF,
    ProductViewXlsx,
    ReceiptsViewList,
    ReceiptsViewAdd,
    ReceiptsViewEdit,
    ReceiptsViewDelete,
    ReceiptsViewPDF,
    ReceiptsViewXlsx,
    ProcurementViewList,
    ProcurementViewAdd,
    ProcurementViewEdit,
    ProcurementViewPaidList,
    ProcurementViewUnpaidList,
    ProcurementViewDelete,
    ProcurementViewPDF,
    ProcurementViewXlsx,
    ServicesViewList,
    ServicesViewAdd,

)

urlpatterns = [
    path('', ComplectationsViewHome.as_view(), name='homepage'),
    path('complectation/add/', ComplectationViewAdd.as_view(), name='complectationaddpage'),
    path('complectation/edit/<str:slug>/', ComplectationViewEdit.as_view(), name='complectationeditpage'),
    path('complectation/delete/<str:slug>/', ComplectationViewDelete.as_view(), name='complectationdeletepage'),

    path('groups/', GroupProductViewList.as_view(), name='groupage'),
    path('groups/add/', GroupProductViewAdd.as_view(), name='grouaddpage'),
    path('groups/edit/<int:pk>', GroupProductViewEdit.as_view(), name='groueditpage'),
    path('groups/delete/<int:pk>', GroupProductViewDelete.as_view(), name='groudeletepage'),

    path('providers/', ProviderViewList.as_view(), name='providerpage'),
    path('providers/add/', ProviderViewAdd.as_view(), name='provideraddpage'),
    path('providers/edit/<int:pk>/', ProviderViewEdit.as_view(), name='providereditpage'),
    path('providers/delete/<int:pk>/', ProviderViewDelete.as_view(), name='providerdeletepage'),

    path('users/', UserViewList.as_view(), name='userpage'),
    path('users/<int:pk>/', UserViewDetale.as_view(), name='userdetalepage'),
    path('users/add/', UserViewAdd.as_view(), name='useraddpage'),
    path('users/edit/<int:pk>/', UserViewEdit.as_view(), name='usereditpage'),
    path('users/delete/<int:pk>/', UserViewDelete.as_view(), name='userdeletepage'),
    path('users/change-password/<int:pk>/', UserPasswordChangeView.as_view(), name='userchangepage'),

    path('products/<str:slug>/', ProductViewList.as_view(), name='productpage'),
    path('products/<str:slug>/<str:group>/', ProductViewListGroup.as_view(), name='productgroupage'),
    path('product/<int:pk>/', ProductViewDetale.as_view(), name='productdetelepage'),
    path('product/add/<int:product_id>/', ProductViewAdd.as_view(), name='productaddpage'),
    path('product/edit/<int:pk>/', ProductViewEdit.as_view(), name='producteditpage'),
    path('product/delete/<int:pk>/', ProductViewDelete.as_view(), name='productdeletepage'),
    path('product/pdf/', ProductViewPDF.as_view(), name='productpdfpage'),
    path('product/xlsx/', ProductViewXlsx.as_view(), name='productxlsxpage'),

    path('receipts/<str:slug>/', ReceiptsViewList.as_view(), name='receiptspage'),
    path('receipts/add/<int:product_id>/', ReceiptsViewAdd.as_view(), name='receiptsaddpage'),
    path('receipts/edit/<int:pk>/', ReceiptsViewEdit.as_view(), name='receiptseditpage'),
    path('receipts/delete/<int:pk>/', ReceiptsViewDelete.as_view(), name='receiptsdeletepage'),
    path('receipts/pdf/<str:slug>/', ReceiptsViewPDF.as_view(), name='receiptspdfpage'),
    path('receipts/xlsx/<str:slug>/', ReceiptsViewXlsx.as_view(), name='receiptsxlsxpage'),

    path('procurements/<str:slug>/', ProcurementViewList.as_view(), name="procurementslistpage"),
    path('procurements/add/<int:product_id>/', ProcurementViewAdd.as_view(), name="procurementsaddpage"),
    path('procurement/edit/<int:pk>/', ProcurementViewEdit.as_view(), name="procurementseditpage"),
    path('procurements/<str:slug>/paid/', ProcurementViewPaidList.as_view(), name="procurementslistpaidpage"),
    path('procurements/<str:slug>/unpaid/', ProcurementViewUnpaidList.as_view(), name="procurementslistunpaidpage"),
    path('procurements/delete/<int:pk>/', ProcurementViewDelete.as_view(), name='procurementsdeletepage'),
    path('procurements/pdf/<str:slug>/', ProcurementViewPDF.as_view(), name='procurementspdfpage'),
    path('procurements/xlsx/<str:slug>/', ProcurementViewXlsx.as_view(), name='procurementsxlsxpage'),

    path('services/<str:slug>/', ServicesViewList.as_view(), name='serviceslistpage'),
    path('services/add/<int:comp_id>', ServicesViewAdd.as_view(), name='servicesaddpage'),

]