# Generated by Django 5.1.2 on 2024-10-21 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя группы')),
                ('slug', models.SlugField(help_text='**Можно использовать толко латинские буквы', max_length=20, unique=True, verbose_name='Ссылка на группу')),
            ],
            options={
                'verbose_name': 'Группа коплектации',
                'verbose_name_plural': 'Группы коплектаций',
            },
        ),
        migrations.CreateModel(
            name='Complectation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя Комплектации')),
                ('adress', models.CharField(max_length=150, verbose_name='Адрес заказчика')),
                ('phone', models.CharField(max_length=15, verbose_name='Телефон заказчика')),
                ('slug', models.SlugField(help_text='**Можно использовать только латинские буквы', max_length=20, unique=True, verbose_name='Ссылка на комплектацию')),
                ('date_create', models.DateField(auto_now=True, verbose_name='Дата создания коплектации')),
                ('balance', models.IntegerField(default=0, verbose_name='Баланс')),
                ('procent', models.IntegerField(default=0, verbose_name='Процент')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Доступ пользователей к комплектации')),
            ],
            options={
                'verbose_name': 'Комплектация',
                'verbose_name_plural': 'Комплектации',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя товара')),
                ('discription', models.TextField(blank=True, null=True, verbose_name='Описание товара')),
                ('count', models.DecimalField(decimal_places=1, default=0, max_digits=12, verbose_name='Количество товаров')),
                ('meas', models.CharField(choices=[('шт', 'штуки'), ('к/м', 'квадратные метры'), ('п/м', 'погоные метры'), ('литр', 'литры'), ('куб', 'кубы'), ('кг', 'килограмы')], default='1', max_length=8, verbose_name='Вид ичесления')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Цена')),
                ('prepayment', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Предоплата')),
                ('remains', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Остаток')),
                ('date_create', models.DateField(auto_now=True, verbose_name='Дата создания товара')),
                ('date_order', models.DateField(blank=True, null=True, verbose_name='Дата заказа товара')),
                ('date_shipment', models.DateField(blank=True, null=True, verbose_name='Дата поставки товара')),
                ('status', models.CharField(choices=[('Не заказано', 'Не заказано'), ('В пути', 'В пути'), ('На складе', 'На складе')], default='Не заказано', max_length=50, verbose_name='Статус товара')),
                ('sklad', models.CharField(blank=True, default=' ', max_length=150, verbose_name='Склад')),
                ('image', models.ImageField(blank=True, upload_to='product/', verbose_name='Картинка товара')),
                ('sum_price_count', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена за все')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор продукта')),
                ('complectation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complectations.complectation', verbose_name='Выберите комплектацию')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='complectations.groupproduct', verbose_name='Группа продукта')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
