# Generated by Django 5.1.2 on 2024-10-27 08:52

import complectations.utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complectations', '0002_provider'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to=complectations.utils.product_image_upload_to, verbose_name='Картинка товара'),
        ),
        migrations.CreateModel(
            name='Receipts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название поступления')),
                ('discription', models.TextField(blank=True, null=True, verbose_name='Описание поступления')),
                ('date_create', models.DateField(verbose_name='Дата поступления')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Сумма поступления')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Добавил поступление')),
                ('complectation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complectations.complectation', verbose_name='Выберите комплектацию')),
            ],
            options={
                'verbose_name': 'Поступление средств',
                'verbose_name_plural': 'Пуступления средств',
            },
        ),
    ]
