# Generated by Django 5.1.2 on 2024-10-28 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complectations', '0003_alter_product_image_receipts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complectation',
            options={'ordering': ['-id'], 'verbose_name': 'Комплектация', 'verbose_name_plural': 'Комплектации'},
        ),
        migrations.AlterModelOptions(
            name='groupproduct',
            options={'ordering': ['-id'], 'verbose_name': 'Группа коплектации', 'verbose_name_plural': 'Группы коплектаций'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-id'], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterModelOptions(
            name='provider',
            options={'ordering': ['-id'], 'verbose_name': 'Поставщик', 'verbose_name_plural': 'Поставщики'},
        ),
        migrations.AlterModelOptions(
            name='receipts',
            options={'ordering': ['-id'], 'verbose_name': 'Поступление средств', 'verbose_name_plural': 'Пуступления средств'},
        ),
        migrations.AlterField(
            model_name='groupproduct',
            name='slug',
            field=models.SlugField(max_length=20, unique=True, verbose_name='Ссылка на группу'),
        ),
        migrations.CreateModel(
            name='Procurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя товара или услуги')),
                ('discription', models.TextField(blank=True, null=True, verbose_name='Описание товара или услуги')),
                ('date_create', models.DateField(verbose_name='Дата добавления чека')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Цена чека')),
                ('price_procent', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Сумма наценки')),
                ('image', models.ImageField(blank=True, upload_to='product/', verbose_name='Фото чека')),
                ('payment_status', models.CharField(choices=[('Оплатил', 'Оплатил'), ('Не оплатил', 'Не оплатил')], max_length=15, verbose_name='Статус оплаты')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('complectation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complectations.complectation', verbose_name='Выберите комплектацию')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='complectations.provider', verbose_name='Выберите поставщика')),
            ],
            options={
                'verbose_name': 'Закупка',
                'verbose_name_plural': 'Закупки',
            },
        ),
    ]
