# Generated by Django 5.1.2 on 2024-10-28 12:01

import complectations.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complectations', '0004_alter_complectation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='procurement',
            name='procent',
            field=models.IntegerField(default=0, verbose_name='Процент %'),
        ),
        migrations.AddField(
            model_name='procurement',
            name='xlsx_file',
            field=models.FileField(blank=True, null=True, upload_to=complectations.utils.procurements_xlsx_upload_to),
        ),
        migrations.AlterField(
            model_name='procurement',
            name='image',
            field=models.ImageField(blank=True, upload_to=complectations.utils.check_img_upload_to, verbose_name='Чек'),
        ),
    ]
