# Generated by Django 5.1.2 on 2024-10-31 16:58

import complectations.utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complectations', '0006_alter_procurement_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя услуги')),
                ('xlsx_file', models.FileField(blank=True, null=True, upload_to=complectations.utils.procurements_xlsx_upload_to, verbose_name='Excel файл сметы')),
                ('discription', models.TextField(blank=True, null=True, verbose_name='Описание услуги')),
                ('date_create', models.DateField(verbose_name='Дата добавления')),
                ('meas', models.CharField(choices=[('шт', 'штуки'), ('к/м', 'квадратные метры'), ('п/м', 'погоные метры'), ('литр', 'литры'), ('куб', 'кубы'), ('кг', 'килограмы')], default='1', max_length=8, verbose_name='Вид исчисления')),
                ('count', models.DecimalField(decimal_places=1, default=0, max_digits=12, verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Цена')),
                ('price_all', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Цена за все')),
                ('procent', models.IntegerField(default=0, verbose_name='Процент %')),
                ('price_procent', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Сумма наценки')),
                ('process_org', models.BooleanField(default=False, verbose_name='Организация процесса')),
                ('payment_status', models.CharField(choices=[('Оплатил', 'Оплатил'), ('Не оплатил', 'Не оплатил')], max_length=15, verbose_name='Статус оплаты')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('complectation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complectations.complectation', verbose_name='Выберите комплектацию')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
    ]
